# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9435c4e865a0f298c908a280bfc4787603e0bb25ee227c8a2d388e0af30eb3cf86a2544059fe7f50630840cec5409b66d84f04ad084105093db800f6461c2c44

test:
  secret_key_base: eb54749428020047a9209c2c0dbb414dc9b941f9e4ab18a67561d77ecb383d431b73f858742508cf3fba48ab6edd3ee3eb98e146c94846fa17d51e64e2ef853a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
